import { IVRPromptStep, LanguageCode } from '../types/ivr';

export const IVR_SCRIPTS: Record<string, IVRPromptStep> = {
  WELCOME: {
    step: 'WELCOME',
    title: 'MoSJE Case Continuity Greeting',
    promptText: {
      hi: 'नमस्कार। यह सामाजिक न्याय और अधिकारिता मंत्रालय, जिला पीड़ित कल्याण प्रकोष्ठ की ओर से आपकी पंजीकृत सहायता मामले के संबंध में एक निर्धारित फॉलो-अप कॉल है।',
      en: 'Namaskar. This is a scheduled follow-up call from the Ministry of Social Justice and Empowerment, District Victim Welfare Cell regarding your registered assistance case.',
      bn: 'নমস্কার। এটি সামাজিক ন্যায়বিচার ও ক্ষমতায়ন মন্ত্রকের জেলা ভিকটিম ওয়েলফেয়ার সেল থেকে আপনার নথিভুক্ত সহায়তা মামলা সম্পর্কিত একটি নির্ধারিত ফলো-আপ কল।',
      ta: 'வணக்கம். இது சமூக நீதி மற்றும் அதிகாரமளித்தல் அமைச்சகத்தின் மாவட்ட பாதிக்கப்பட்டோர் நலப் பிரிவில் இருந்து உங்கள் வழக்கு தொடர்பான திட்டமிடப்பட்ட தொடர்பு அழைப்பு.',
      te: 'నమస్కారం. సామాజిక న్యాయం మరియు సాధికారత మంత్రిత్వ శాఖ, జిల్లా బాధితుల సంక్షేమ విభాగం నుండి మీ నమోదిత కేసు సహాయం కోసం ఇది షెడ్యూల్ చేసిన ఫాలో-అప్ కాల్.',
      mr: 'नमस्कार. सामाजिक न्याय आणि सक्षमीकरण मंत्रालय, जिल्हा पीडित कल्याण कक्षाकडून आपल्या नोंदणीकृत सहाय्यता प्रकरणाबाबत हा नियोजित फॉलो-अप कॉल आहे.',
      kn: 'ನಮಸ್ಕಾರ. ಇದು ಸಾಮಾಜಿಕ ನ್ಯಾಯ ಮತ್ತು ಸಬಲೀಕರಣ ಸಚಿವಾಲಯದ ಜಿಲ್ಲಾ ಸಂತ್ರಸ್ತರ ಕಲ್ಯಾಣ ಕೋಶದಿಂದ ನಿಮ್ಮ ನೆರವು ಪ್ರಕರಣದ ಕುರಿತಾದ ನಿಗದಿತ ಫಾಲೋ-ಅಪ್ ಕರೆ.',
      gu: 'નમસ્કાર. આ સામાજિક ન્યાય અને સશક્તિકરણ મંત્રાલય, જિલ્લા પીડિત કલ્યાણ કક્ષ તરફથી તમારા નોંધાયેલા સહાય કેસ સંબંધિત નિર્ધારિત ફોલો-અપ કૉલ છે.',
      or: 'ନମସ୍କାର। ଏହା ସାମାଜିକ ନ୍ୟାୟ ଏବଂ ସଶକ୍ତୀକରଣ ମନ୍ତ୍ରଣାଳୟ, ଜିଲ୍ଲା ପୀଡ଼ିତ କଲ୍ୟାଣ ପ୍ରକୋଷ୍ଠ ତରଫରୁ ଆପଣଙ୍କ ପଞ୍ଜୀକୃତ ସହାୟତା ମାମଲା ସମ୍ବନ୍ଧୀୟ ଏକ ନିର୍ଦ୍ଧାରିତ ଫଲୋ-ଅପ୍ କଲ୍।',
    },
    romanizedPromptText: {
      hi: 'Namaskar. Yeh Samajik Nyay aur Adhikarita Mantralaya, zilla pidit kalyan prakoshth ki or se aapke panjikrit sahayata mamle ke sambandh mein nirdharit follow-up call hai.',
      bn: 'Nomoshkar. Eti Samajik Nyaybichar o Khomotayon Montronaloy theke apnar sahajyo mamla somporkito scheduled follow-up call.',
      ta: 'Vanakkam. Idhu Samooka Neethi Matrum Athikarathalithal Amaichagathilirundhu ungal vazhakku thodarpana scheduled call.',
      te: 'Namaskaram. Samajika Nyayam mariyu Sadhikarata Mantrithva Shakha nundi mee sahayam kosam idi scheduled follow-up call.',
      mr: 'Namaskar. Samajik Nyay aani Sakshamikaran Mantralay, jilha kalyan kakshatun aaplya nondanikrit sahayyata prakaranababt ha call ahe.',
      kn: 'Namaskara. Idu Samajika Nyaya mattu Sabalikarana Sachivalayadinda nimma sahayada prakaranada kuritada call.',
      gu: 'Namaskar. Aa Samajik Nyay ane Sashaktikaran Mantralay tarafthi tamara nondhayela sahay case sambandhit follow-up call chhe.',
      or: 'Namaskar. Eha Samajika Nyaya o Sashaktikarana Mantralaya tarafru apananka panjikruta sahayata mamala sambandhita call.',
    },
  },

  CONSENT_CHECK: {
    step: 'CONSENT_CHECK',
    title: 'Privacy, Safety & Informed Consent',
    promptText: {
      hi: 'आगे बढ़ने से पहले, क्या यह आपके लिए बात करने का सुरक्षित और सुविधाजनक समय है? यदि आप अभी बात कर सकते हैं, तो 1 दबाएं। यदि आप चाहते हैं कि हम कल दोबारा कॉल करें, तो 2 दबाएं। यदि आप कॉल रोकना या बंद करना चाहते हैं, तो 9 दबाएं।',
      en: 'Before we proceed, is this a safe, private, and comfortable time for you to speak? Press 1 if you can speak right now. Press 2 if you would like us to call you back tomorrow. Press 9 to pause or opt out of these check-in calls.',
      bn: 'শুরু করার আগে, এটি কি আপনার কথা বলার জন্য নিরাপদ ও সুবিধাজনক সময়? এখনই কথা বলতে চাইলে ১ টিপুন। কাল আবার কল করার জন্য ২ টিপুন। কল বন্ধ বা বিরতি দিতে ৯ টিপুন।',
      ta: 'தொடங்குவதற்கு முன், இது நீங்கள் பேசுவதற்கு பாதுகாப்பான மற்றும் வசதியான நேரமா? இப்போது பேச 1 ஐ அழுத்தவும். நாளை மீண்டும் அழைக்க 2 ஐ அழுத்தவும். அழைப்புகளை நிறுத்த 9 ஐ அழுத்தவும்.',
      te: 'ముందుకు వెళ్లేముందు, ఇది మీరు మాట్లాడటానికి సురక్షితమైన మరియు అనుకూలమైన సమయమా? ఇప్పుడే మాట్లాడటానికి 1 నొక్కండి. రేపు తిరిగి కాల్ చేయాలనుకుంటే 2 నొక్కండి. కాల్స్ నిలిపివేయడానికి 9 నొక్కండి.',
      mr: 'पुढे जाण्यापूर्वी, ही आपल्यासाठी बोलण्याची सुरक्षित व सोयीस्कर वेळ आहे का? आत्ता बोलू शकत असल्यास 1 दाबा. उद्या पुन्हा कॉल करायचा असल्यास 2 दाबा. कॉल थांबवायचे असल्यास 9 दाबा.',
      kn: 'ಮುಂದುವರಿಯುವ ಮುನ್ನ, ಇದು ನೀವು ಮಾತನಾಡಲು ಸುರಕ್ಷಿತ ಮತ್ತು ಅನುಕೂಲಕರ ಸಮಯವೇ? ಈಗ ಮಾತನಾಡಲು 1 ಒತ್ತಿ. ನಾಳೆ ಮರಳಿ ಕರೆ ಮಾಡಲು 2 ಒತ್ತಿ. ಕರೆಗಳನ್ನು ನಿಲ್ಲಿಸಲು 9 ಒತ್ತಿ.',
      gu: 'આગળ વધતા પહેલા, શું આ તમારા માટે વાત કરવાનો સુરક્ષિત અને અનુકૂળ સમય છે? અત્યારે વાત કરી શકો તો 1 દબાવો. કાલે ફરી કૉલ કરવા માટે 2 દબાવો. કૉલ બંધ કરવા માટે 9 દબાવો.',
      or: 'ଆଗକୁ ବଢ଼ିବା ପୂର୍ବରୁ, ଏହା କଥା ହେବା ପାଇଁ ଏକ ସୁରକ୍ଷିତ ଏବଂ ସୁବିଧାଜନକ ସମୟ କି? ଏବେ କଥା ହେବା ପାଇଁ 1 ଦବାନ୍ତୁ। କାଲି ପୁଣି କଲ୍ କରିବା ପାଇଁ 2 ଦବାନ୍ତୁ। କଲ୍ ବନ୍ଦ କରିବାକୁ 9 ଦବାନ୍ତୁ।',
    },
    romanizedPromptText: {
      hi: 'Aage badhne se pehle, kya yeh aapke liye baat karne ka surakshit samay hai? Agar aap abhi baat kar sakte hain, toh 1 dabayein. Kal dobaara call ke liye 2 dabayein. Call rokne ke liye 9 dabayein.',
      bn: 'Shuru korar aage, eti ki apnar kotha bolar safe shomoy? Ekhon kotha bolte 1 tipeen. Kal abar call-er jonno 2 tipeen. Call bondho korte 9 tipeen.',
      ta: 'Thodangum mun, idhu neengal pesa safe aana nerama? Ippo pesa 1 ai azhuthavum. Naalai call seiya 2 ai azhuthavum. Call nirutha 9 ai azhuthavum.',
      te: 'Munduku velley mundu, idi meeru matladataniki safe samayama? Ippudu matladataniki 1 nokkandi. Repu malli call cheyataniki 2 nokkandi. Call apataniki 9 nokkandi.',
      mr: 'Pudhe janyapurvi, hi aapplyasathi bolnyachi surakshit vel ahe ka? Aatta bolu shakat aslyas 1 daba. Udya punha call sathi 2 daba. Call thambvanyasathi 9 daba.',
      kn: 'Munduvaryuva munna, idu neevu matanadalu safe samayave? Eega matanadalu 1 otti. Naale marali call madalu 2 otti. Call nillisaloo 9 otti.',
      gu: 'Aagad vadhta pahela, shu aa tamare vaat karva mate safe samay chhe? Atyare vaat kari shako to 1 dabavo. Kale farithi call mate 2 dabavo. Call bandh karva 9 dabavo.',
      or: 'Agaku badhiba purbaru, eha katha heba pain safe samaya ki? Ebe katha heba pain 1 dabantu. Kali puni call pain 2 dabantu. Call band pain 9 dabantu.',
    },
    options: [
      {
        key: '1',
        label: {
          hi: '1: हाँ, सुरक्षित है (जारी रखें)',
          en: '1: Yes, safe to proceed',
          bn: '১: হ্যাঁ, নিরাপদ (চালিয়ে যান)',
          ta: '1: ஆம், பேசலாம்',
          te: '1: అవును, మాట్లాడవచ్చు',
          mr: '1: हो, सुरक्षित आहे (सुरु ठेवा)',
          kn: '1: ಹೌದು, ಮಾತನಾಡಬಹುದು',
          gu: '1: હા, વાત કરી શકીએ છીએ',
          or: '1: ହଁ, କଥା ହୋଇପାରିବି',
        },
        actionDescription: 'Proceed with assessment',
      },
      {
        key: '2',
        label: {
          hi: '2: कल दोबारा कॉल करें',
          en: '2: Call back tomorrow',
          bn: '২: কাল আবার কল করুন',
          ta: '2: நாளை அழைக்கவும்',
          te: '2: రేపు కాల్ చేయండి',
          mr: '2: उद्या पुन्हा कॉल करा',
          kn: '2: ನಾಳೆ ಮರಳಿ ಕರೆ ಮಾಡಿ',
          gu: '2: કાલે ફરી કૉલ કરો',
          or: '2: କାଲି ପୁଣି କଲ୍ କରନ୍ତୁ',
        },
        actionDescription: 'Reschedule check-in for next day',
      },
      {
        key: '9',
        label: {
          hi: '9: कॉल रोकें / ऑप्ट-आउट करें',
          en: '9: Pause / Opt out of calls',
          bn: '৯: কল বন্ধ রাখুন',
          ta: '9: அழைப்புகளை நிறுத்துக',
          te: '9: కాల్స్ ఆపివేయండి',
          mr: '9: कॉल थांबवा / ऑप्ट-आउट',
          kn: '9: ಕರೆಗಳನ್ನು ನಿಲ್ಲಿಸಿ',
          gu: '9: કૉલ બંધ કરો / ઑપ્ટ-આઉટ',
          or: '9: କଲ୍ ବନ୍ଦ କରନ୍ତୁ / ଅପ୍ଟ-ଆଉଟ୍',
        },
        actionDescription: 'Respect citizen choice and pause check-ins',
      },
    ],
  },

  STATUS_ASSESSMENT: {
    step: 'STATUS_ASSESSMENT',
    title: 'Self-Reported Well-being & Coping',
    promptText: {
      hi: 'हम सीधे आपसे जानना चाहते हैं कि इस सप्ताह आप कैसा महसूस कर रहे हैं और स्थिति से कैसे निपट रहे हैं? यदि आप सामान्य और स्थिर महसूस कर रहे हैं, तो 1 दबाएं। यदि आप तनाव, चिंता या कठिनाई महसूस कर रहे हैं, तो 2 दबाएं। यदि आप अत्यधिक संकट या आपातकालीन स्थिति में हैं, तो 3 दबाएं।',
      en: 'We want to ask you directly how you are feeling and coping this week. Press 1 if you are coping well and feel stable. Press 2 if you are experiencing distress, anxiety, or difficulties. Press 3 if you are in severe crisis or urgently need assistance.',
      bn: 'আমরা সরাসরি আপনার কাছ থেকে জানতে চাই এই সপ্তাহে আপনি কেমন আছেন। আপনি স্বাভাবিক থাকলে ১ টিপুন। মানসিক চাপ বা উদ্বেগে থাকলে ২ টিপুন। তীব্র সংকটে বা জরুরি সাহায্যে থাকলে ৩ টিপুন।',
      ta: 'இந்த வாரம் நீங்கள் எப்படி உணர்கிறீர்கள் என்பதை நேரடியாக அறிய விரும்புகிறோம். நலமாக இருந்தால் 1 ஐ அழுத்தவும். மன அழுத்தம் அல்லது சிரமம் இருந்தால் 2 ஐ அழுத்தவும். தீவிர அவசர உதவி தேவைப்பட்டால் 3 ஐ அழுத்தவும்.',
      te: 'ఈ వారం మీరు ఎలా ఉన్నారో నేరుగా మీ నుండి తెలుసుకోవాలనుకుంటున్నాము. సాధారణంగా మరియు ప్రశాంతంగా ఉంటే 1 నొక్కండి. ఒత్తిడి లేదా ఇబ్బందులు ఎదుర్కొంటుంటే 2 నొక్కండి. అత్యవసర సహాయం కావాలంటే 3 నొక్కండి.',
      mr: 'या आठवड्यात आपण कसे आहात आणि परिस्थिती कशी हाताळत आहात हे आम्हाला थेट आपल्याकडून जाणून घ्यायचे आहे. ठीक असल्यास 1 दाबा. ताण किंवा अडचण वाटत असल्यास 2 दाबा. तीव्र संकटात असल्यास 3 दाबा.',
      kn: 'ಈ ವಾರ ನೀವು ಹೇಗೆ ಅನುಭವಿಸುತ್ತಿದ್ದೀರಿ ಎಂಬುದನ್ನು ನೇರವಾಗಿ ನಿಮ್ಮಿಂದ ತಿಳಿಯಲು ಬಯಸುತ್ತೇವೆ. ಚೆನ್ನಾಗಿದ್ದರೆ 1 ಒತ್ತಿ. ಆತಂಕ ಅಥವಾ ತೊಂದರೆಗಳಿದ್ದರೆ 2 ಒತ್ತಿ. ತುರ್ತು ನೆರವು ಬೇಕಿದ್ದರೆ 3 ಒತ್ತಿ.',
      gu: 'આ અઠવાડિયે તમે કેવું અનુભવી રહ્યા છો તે સીધું તમારા મોઢે જાણવા માંગીએ છીએ. સ્થિતિ સામાન્ય હોય તો 1 દબાવો. તણાવ કે મુશ્કેલી હોય તો 2 દબાવો. ગંભીર કટોકટીમાં હોવ તો 3 દબાવો.',
      or: 'ଏହି ସପ୍ତାହରେ ଆପଣ କିପରି ଅନୁଭବ କରୁଛନ୍ତି ତାହା ସିଧାସଳଖ ଜାଣିବାକୁ ଚାହୁଁ। ଯଦି ଆପଣ ଠିକ୍ ଅଛନ୍ତି, 1 ଦବାନ୍ତୁ। ଯଦି ଚାପ ବା ଅସୁବିଧାରେ ଅଛନ୍ତି, 2 ଦବାନ୍ତୁ। ଅତି ଜରୁରୀ ସହାୟତା ଆବଶ୍ୟକ ଥିଲେ 3 ଦବାନ୍ତୁ।',
    },
    romanizedPromptText: {
      hi: 'Hum aapse jaanna chahte hain ki iss hafte aap kaisa mehsoos kar rahe hain? Agar aap theek aur sthir mehsoos kar rahe hain, toh 1 dabayein. Agar aap tanav ya kathinai mehsoos kar rahe hain, toh 2 dabayein. Agar aap aapatkaleen sthiti ya sankat mein hain, toh 3 dabayein.',
      bn: 'Ei shoptaho-te aapni kemon aachen? Shavabik thakle 1 tipeen. Chap ba udveg thakle 2 tipeen. Bipod ba joruri sahayye 3 tipeen.',
      ta: 'Indha vaaram neengal eppadi unargireergal? Nalamaaga irundhaal 1 ai azhuthavum. Manavazhutham irundhaal 2 ai azhuthavum. Theevira avasaram endraal 3 ai azhuthavum.',
      te: 'Ee vaaram meeru ela unnaru? Bagane unte 1 nokkandi. Ottidi unte 2 nokkandi. Theevira sankshebam unte 3 nokkandi.',
      mr: 'Aaplyala ya aathvadyat kase vatat ahe? Theek vatat aslyas 1 daba. Taan vatat aslyas 2 daba. Gambhir sankat aslyas 3 daba.',
      kn: 'Ee vaara neevu hege iddira? Channagiddare 1 otti. Othada iddare 2 otti. Theevra thondare iddare 3 otti.',
      gu: 'Aa athvadiye tame kevu anubhavo chho? Saru hoy to 1 dabavo. Tanav hoy to 2 dabavo. Gambhir samasya hoy to 3 dabavo.',
      or: 'Ei saptaha-re apana kemiti achhanti? Thik thile 1 dabantu. Chapa-re thile 2 dabantu. Atyanta joruri sahayata pain 3 dabantu.',
    },
    options: [
      {
        key: '1',
        label: {
          hi: '1: सामान्य / स्थिति ठीक है',
          en: '1: Coping adequately / Stable',
          bn: '১: স্বাভাবিক / ঠিক আছি',
          ta: '1: நலமாக உள்ளேன்',
          te: '1: బాగానే ఉన్నాను',
          mr: '1: सामान्य / ठीक आहे',
          kn: '1: ಚೆನ್ನಾಗಿದ್ದೇನೆ',
          gu: '1: સામાન્ય / સારું છે',
          or: '1: ସ୍ଥିତି ଠିକ୍ ଅଛି',
        },
        actionDescription: 'Recorded as coping well',
      },
      {
        key: '2',
        label: {
          hi: '2: तनाव या कठिनाई महसूस हो रही है',
          en: '2: Experiencing stress / Difficulties',
          bn: '২: মানসিক চাপ বা উদ্বেগ',
          ta: '2: மன அழுத்தம் / சிரமம்',
          te: '2: ఒత్తిడి లేదా ఆందోళన',
          mr: '2: ताण किंवा अडचणी आहेत',
          kn: '2: ಒತ್ತಡ / ತೊಂದರೆ ಇದೆ',
          gu: '2: તણાવ કે મુશ્કેલી છે',
          or: '2: ଚାପ ବା ଅସୁବିଧା ଅନୁଭବ',
        },
        actionDescription: 'Recorded as moderate distress',
      },
      {
        key: '3',
        label: {
          hi: '3: गंभीर संकट / तत्काल मदद चाहिए',
          en: '3: Severe crisis / Immediate assistance',
          bn: '৩: তীব্র সংকট / জরুরি সাহায্য চাই',
          ta: '3: அவசர உதவி தேவை',
          te: '3: తీవ్ర సంక్షోభం / అత్యవసరం',
          mr: '3: गंभीर संकट / त्वरित मदत हवी',
          kn: '3: ತೀವ್ರ ಬಿಕ್ಕಟ್ಟು / ತಕ್ಷಣದ ಸಹಾಯ',
          gu: '3: ગંભીર કટોકટી / તાત્કાલિક મદદ',
          or: '3: ଅତି ଜରୁରୀ ସହାୟତା ଆବଶ୍ୟକ',
        },
        actionDescription: 'Trigger immediate priority escalation in caseworker queue',
      },
    ],
  },

  NEEDS_SELECTION: {
    step: 'NEEDS_SELECTION',
    title: 'Self-Reported Assistance Requirements',
    promptText: {
      hi: 'इस समय आपको किस विशिष्ट सहायता की आवश्यकता है? कानूनी सहायता या न्यायालय सुरक्षा के लिए 1 दबाएं। मनोवैज्ञानिक परामर्श के लिए 2 दबाएं। धमकी या पुलिस सुरक्षा के लिए 3 दबाएं। धारा 15ए राहत राशि भुगतान जानकारी के लिए 4 दबाएं। यदि वर्तमान में किसी सहायता की आवश्यकता नहीं है, तो 5 दबाएं।',
      en: 'What specific support do you require from your District Welfare Officer? Press 1 for Legal Aid or Court Hearing protection escort. Press 2 for Trauma Counselling or Mental Health support. Press 3 for Police Protection or Witness Security. Press 4 for Section 15A Relief Compensation disbursement follow-up. Press 5 if no specific assistance is needed right now.',
      bn: 'আপনার এখন কী ধরনের সহায়তার প্রয়োজন? আইনি সাহায্য বা আদালত নিরাপত্তার জন্য ১ টিপুন। কাউন্সেলিং-এর জন্য ২ টিপুন। পুলিশ সুরক্ষার জন্য ৩ টিপুন। ক্ষতিপূরণের তথ্যের জন্য ৪ টিপুন। কোনো সহায়তার প্রয়োজন না থাকলে ৫ টিপুন।',
      ta: 'உங்களுக்கு என்ன குறிப்பிட்ட உதவி தேவை? சட்ட உதவி அல்லது நீதிமன்ற பாதுகாப்பிற்கு 1 ஐ அழுத்தவும். மனநல ஆலோசனைக்கு 2 ஐ அழுத்தவும். காவல்துறை பாதுகாப்பிற்கு 3 ஐ அழுத்தவும். நிவாரண உதவித்தொகை விபரத்திற்கு 4 ஐ அழுத்தவும். உதவி தேவையில்லை என்றால் 5 ஐ அழுத்தவும்.',
      te: 'మీకు ప్రస్తుతం ఏ సహాయం కావాలి? న్యాయ సహాయం లేదా కోర్టు భద్రత కోసం 1 నొక్కండి. మానసిక కౌన్సెలింగ్ కోసం 2 నొక్కండి. పోలీసు రక్షణ కోసం 3 నొక్కండి. ఉపశమన పరిహారం సమాచారం కోసం 4 నొక్కండి. ఎలాంటి సహాయం అవసరం లేకపోతే 5 నొక్కండి.',
      mr: 'आपल्याला कोणत्या विशिष्ट मदतीची गरज आहे? कायदेशीर मदत किंवा न्यायालय संरक्षणासाठी 1 दाबा. मानसोपचार समुपदेशनासाठी 2 दाबा. पोलीस संरक्षणासाठी 3 दाबा. नुकसानभरपाई सहाय्यासाठी 4 दाबा. मदतीची गरज नसल्यास 5 दाबा.',
      kn: 'ನಿಮಗೆ ಯಾವ ನಿರ್ದಿಷ್ಟ ನೆರವು ಅಗತ್ಯವಿದೆ? ಕಾನೂನು ನೆರವು ಅಥವಾ ನ್ಯಾಯಾಲಯ ಭದ್ರತೆಗೆ 1 ಒತ್ತಿ. ಮಾನಸಿಕ ಸಮಾಲೋಚನೆಗೆ 2 ಒತ್ತಿ. ಪೊಲೀಸ್ ಭದ್ರತೆಗೆ 3 ಒತ್ತಿ. ಪರಿಹಾರ ನಿಧಿ ಮಾಹಿತಿಗೆ 4 ಒತ್ತಿ. ನೆರವು ಅಗತ್ಯವಿಲ್ಲದಿದ್ದರೆ 5 ಒತ್ತಿ.',
      gu: 'તમને કઈ ચોક્કસ સહાયની જરૂર છે? કાનૂની સહાય અથવા કોર્ટ સુરક્ષા માટે 1 દબાવો. કાઉન્સેલિંગ માટે 2 દબાવો. પોલીસ સુરક્ષા માટે 3 દબાવો. વળતર સહાયની વિગત માટે 4 દબાવો. કોઈ સહાયની જરૂર ન હોય તો 5 દબાવો.',
      or: 'ଆପଣଙ୍କୁ କେଉଁ ନିର୍ଦ୍ଦିଷ୍ଟ ସହାୟତା ଆବଶ୍ୟକ? ଆଇନଗତ ସହାୟତା କିମ୍ବା କୋର୍ଟ ସୁରକ୍ଷା ପାଇଁ 1 ଦବାନ୍ତୁ। ମାନସିକ ପରାମର୍ଶ ପାଇଁ 2 ଦବାନ୍ତୁ। ପୋଲିସ ସୁରକ୍ଷା ପାଇଁ 3 ଦବାନ୍ତୁ। କ୍ଷତିପୂରଣ ସୂଚନା ପାଇଁ 4 ଦବାନ୍ତୁ। କିଛି ଆବଶ୍ୟକ ନଥିଲେ 5 ଦବାନ୍ତୁ।',
    },
    romanizedPromptText: {
      hi: 'Aapko kis sahayata ki aavashyakta hai? Kanooni sahayata ke liye 1 dabayein. Mansik paramarsh ke liye 2 dabayein. Police suraksha ke liye 3 dabayein. Section 15A rahat rashi jankari ke liye 4 dabayein. Madad ki zaroorat nahi hai toh 5 dabayein.',
      bn: 'Apnar kiser proyojon? Aaini sahayyey 1 tipeen. Counselling-e 2 tipeen. Police shurokkhaye 3 tipeen. Section 15A khetipuran-e 4 tipeen. Proyojon na thakle 5 tipeen.',
      ta: 'Ungalukku enna udhavi thevai? Satta udhavikku 1 ai azhuthavum. Mananala aalosanikku 2 ai azhuthavum. Kaavalthurai paadhukaappukku 3 ai azhuthavum. Nivarana thogai vivarathukku 4 ai azhuthavum. Thevai illai endraal 5 ai azhuthavum.',
      te: 'Meeku elaanti sahayam kavali? Nyaya sahayam kosam 1 nokkandi. Manasika counseling kosam 2 nokkandi. Police rakshana kosam 3 nokkandi. Section 15A pariharam kosam 4 nokkandi. Emi avasaram lekapothe 5 nokkandi.',
      mr: 'Aaplyas kontya madatichi garaj ahe? Kaydesheer madateesathi 1 daba. Mansopchar samupdeshanasathi 2 daba. Police sanrakshanasathi 3 daba. Section 15A nuksaanbharpaisathi 4 daba. Garaj naslyas 5 daba.',
      kn: 'Nimge yaava sahaya beku? Kanoonu sahayakke 1 otti. Manasika samalochanege 2 otti. Police bhadrathege 3 otti. Section 15A pariharake 4 otti. Sahaya bedavendare 5 otti.',
      gu: 'Tamne kai sahay jaruri chhe? Kanooni sahay mate 1 dabavo. Mansik counselling mate 2 dabavo. Police suraksha mate 3 dabavo. Section 15A vadhtar sahay mate 4 dabavo. Jarur na hoy to 5 dabavo.',
      or: 'Apananku kouthi darkar? Ainagata sahayata pain 1 dabantu. Manasika paramarsha pain 2 dabantu. Police suraksha pain 3 dabantu. Section 15A kshatipurana pain 4 dabantu. Darkar nathile 5 dabantu.',
    },
    options: [
      {
        key: '1',
        label: {
          hi: '1: विधिक सहायता / कोर्ट एस्कॉर्ट',
          en: '1: Legal Aid & Court Escort',
          bn: '১: আইনি সাহায্য ও কোর্ট এসকর্ট',
          ta: '1: சட்ட உதவி & நீதிமன்ற பாதுகாப்பு',
          te: '1: న్యాయ సహాయం & కోర్టు భద్రత',
          mr: '1: कायदेशीर मदत आणि कोर्ट एस्कॉर्ट',
          kn: '1: ಕಾನೂನು ನೆರವು & ಕೋರ್ಟ್ ಭದ್ರತೆ',
          gu: '1: કાનૂની સહાય અને કોર્ટ એસ્કોર્ટ',
          or: '1: ଆଇନଗତ ସହାୟତା ଏବଂ କୋର୍ଟ ଏସ୍କର୍ଟ',
        },
        actionDescription: 'Request legal aid & trial date protection',
      },
      {
        key: '2',
        label: {
          hi: '2: मानसिक स्वास्थ्य / परामर्श',
          en: '2: Trauma Counselling & Therapy',
          bn: '২: ট্রমা কাউন্সেলিং ও মানসিক স্বাস্থ্য',
          ta: '2: மனநல ஆலோசனை & சிகிச்சை',
          te: '2: మానసిక కౌన్సెలింగ్',
          mr: '2: मानसिक आरोग्य समुपदेशन',
          kn: '2: ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಮಾಲೋಚನೆ',
          gu: '2: માનસિક આરોગ્ય અને પરામર્શ',
          or: '2: ମାନସିକ ପରାମର୍ଶ',
        },
        actionDescription: 'Request designated clinical trauma counsellor',
      },
      {
        key: '3',
        label: {
          hi: '3: पुलिस सुरक्षा / गवाह संरक्षण',
          en: '3: Police Protection & Witness Security',
          bn: '৩: পুলিশ সুরক্ষা ও সাক্ষী নিরাপত্তা',
          ta: '3: காவல்துறை பாதுகாப்பு & சாட்சி பாதுகாப்பு',
          te: '3: పోలీసు రక్షణ & సాక్షుల భద్రత',
          mr: '3: पोलीस संरक्षण आणि साक्षीदार सुरक्षा',
          kn: '3: ಪೊಲೀಸ್ ರಕ್ಷಣೆ & ಸಾಕ್ಷಿ ಭದ್ರತೆ',
          gu: '3: પોલીસ સુરક્ષા અને સાક્ષી સંરક્ષણ',
          or: '3: ପୋଲିସ ସୁରକ୍ଷା ଏବଂ ସାକ୍ଷୀ ସୁରକ୍ଷା',
        },
        actionDescription: 'Flag critical witness security escalation to SP / Welfare Cell',
      },
      {
        key: '4',
        label: {
          hi: '4: धारा 15ए राहत राशि भुगतान',
          en: '4: Compensation Disbursement (Sec 15A)',
          bn: '৪: ক্ষতিপূরণ অর্থপ্রদান (ধারা ১৫এ)',
          ta: '4: நிவாரணத் தொகை (பிரிவு 15A)',
          te: '4: పరిహారం విడుదల (సెక్షన్ 15A)',
          mr: '4: नुकसानभरपाई वितरण (कलम 15A)',
          kn: '4: ಪರಿಹಾರ ವಿತರಣೆ (ಸೆಕ್ಷನ್ 15A)',
          gu: '4: વળતર સહાય ચૂકવણી (કલમ 15A)',
          or: '4: କ୍ଷତିପୂରଣ ପ୍ରଦାନ (ଧାରା 15A)',
        },
        actionDescription: 'Check status of pending DBTL / treasury release',
      },
      {
        key: '5',
        label: {
          hi: '5: अभी किसी सहायता की आवश्यकता नहीं',
          en: '5: No specific needs right now',
          bn: '৫: এখন কোনো সাহায্যের প্রয়োজন নেই',
          ta: '5: இப்போது எதுவும் தேவையில்லை',
          te: '5: ప్రస్తుతం ఏమీ అవసరం లేదు',
          mr: '5: सध्यातरी मदतीची गरज नाही',
          kn: '5: ಸದ್ಯಕ್ಕೆ ಯಾವುದೇ ನೆರವು ಬೇಕಿಲ್ಲ',
          gu: '5: અત્યારે કોઈ જરૂર નથી',
          or: '5: ଏବେ କିଛି ଆବଶ୍ୟକ ନାହିଁ',
        },
        actionDescription: 'Logged without pending requirement',
      },
    ],
  },

  VOICE_MESSAGE: {
    step: 'VOICE_MESSAGE',
    title: 'Spoken Audio Note for Welfare Officer',
    promptText: {
      hi: 'यदि आप अपने जिला कल्याण अधिकारी के लिए कोई विशेष संदेश छोड़ना चाहते हैं, तो बीप के बाद बोलें। समाप्त करने के लिए कोई भी कुंजी या हैश (#) दबाएं। यदि संदेश नहीं छोड़ना चाहते तो सीधे हैश (#) दबाएं।',
      en: 'If you wish to record a short voice message or mention details for your District Welfare Officer, please speak after the beep. Press hash (#) or any key when done. If not, press hash (#) to continue.',
      bn: 'আপনি যদি আপনার জেলা কল্যাণ কর্মকর্তার জন্য কোনো বার্তা রেকর্ড করতে চান, তবে বিপের পর বলুন। শেষ করতে হ্যাশ (#) টিপুন। বার্তা দিতে না চাইলে সরাসরি হ্যাশ (#) টিপুন।',
      ta: 'உங்கள் மாவட்ட நல அதிகாரியிடம் கூற விரும்பும் செய்தியை பீப் ஒலிக்கு பின் பேசவும். முடிக்க # ஐ அழுத்தவும். செய்தி தேவையில்லை என்றால் நேரடியாக # ஐ அழுத்தவும்.',
      te: 'మీ జిల్లా సంక్షేమ అధికారికి ఏదైనా సందేశం ఇవ్వాలనుకుంటే, బీప్ తర్వాత మాట్లాడండి. ముగించడానికి # నొక్కండి. సందేశం ఇవ్వకపోతే నేరుగా # నొక్కండి.',
      mr: 'आपल्या जिल्हा कल्याण अधिकाऱ्यासाठी काही संदेश द्यायचा असल्यास बीप नंतर बोला. पूर्ण झाल्यावर # दाबा. संदेश नसेल तर थेट # दाबा.',
      kn: 'ನಿಮ್ಮ ಜಿಲ್ಲಾ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿಗೆ ಯಾವುದೇ ಸಂದೇಶ ತಿಳಿಸಬೇಕಿದ್ದರೆ, ಬೀಪ್ ನಂತರ ಮಾತನಾಡಿ. ಮುಗಿಸಲು # ಒತ್ತಿ. ಸಂದೇಶವಿಲ್ಲದಿದ್ದರೆ ನೇರವಾಗಿ # ಒತ್ತಿ.',
      gu: 'તમારા જિલ્લા કલ્યાણ અધિકારી માટે સંદેશ આપવો હોય તો બીપ પછી બોલો. પૂર્ણ કરવા માટે # દબાવો. સંદેશ ન આપવો હોય તો સીધું # દબાવો.',
      or: 'ଆପଣଙ୍କ ଜିଲ୍ଲା କଲ୍ୟାଣ ଅଧିକାରୀଙ୍କ ପାଇଁ କିଛି କହିବାକୁ ଚାହୁଁଥିଲେ, ବିପ୍ ପରେ କୁହନ୍ତୁ। ଶେଷ କରିବାକୁ # ଦବାନ୍ତୁ। କିଛି କହିବାକୁ ନଥିଲେ ସିଧା # ଦବାନ୍ତୁ।',
    },
    romanizedPromptText: {
      hi: 'Yadi aap apne Zilla Kalyan Adhikari ke liye koi vishesh sandesh chhodna chahte hain, toh beep ke baad bolein. Samapt karne ke liye hash (#) dabayein.',
      bn: 'Apnar Zilla Kalyan Adhikarir jonno barta dite chaile beep-er por bolun. Shesh korte hash (#) tipeen.',
      ta: 'Ungal Maavatta Nala Adhikariku seithi koora virumbinaal beep pin pesavum. Mudikka hash (#) ai azhuthavum.',
      te: 'Meeru Zilla Kshema Adhikariki sandesham ivvalanukunte beep tharuvatha matladandi. Muginchataniki hash (#) nokkandi.',
      mr: 'Aaplya Jilha Kalyan Adhikaryasathi sandesh dyaycha aslyas beep nantar bola. Purna jhalyaavr hash (#) daba.',
      kn: 'Nimma Jilla Kalyana Adhikarige sandesha thilisabekiddare beep nanthara matanadi. Mugisalu hash (#) otti.',
      gu: 'Tamara Jilla Kalyan Adhikari mate sandesh aapvo hoy to beep pachhi bolo. Purna karva mate hash (#) dabavo.',
      or: 'Apananka Jilla Kalyana Adhikarinka pain sandesha debaku chahuthile beep pare kahantu. Shesha pain hash (#) dabantu.',
    },
  },

  CONFIRMATION: {
    step: 'CONFIRMATION',
    title: 'Acknowledgment & Citizen Agency Rights',
    promptText: {
      hi: 'धन्यवाद। आपका अनुरोध और जानकारी सुरक्षित रूप से आपके जिला कल्याण अधिकारी को भेज दी गई है। आप किसी भी समय अपनी संपर्क प्राथमिकताएं बदलने या अपना रिकॉर्ड देखने का अधिकार रखते हैं। अपना ध्यान रखें।',
      en: 'Thank you. Your self-reported status and requested support have been securely registered and notified to your designated District Welfare Officer. You retain full rights to inspect, update, or pause your check-in records at any time. Stay safe.',
      bn: 'ধন্যবাদ। আপনার তথ্য ও অনুরোধ নিরাপদে আপনার জেলা কর্মকর্তার কাছে পৌঁছে গেছে। আপনি যে কোনো সময় আপনার পছন্দের পরিবর্তন করতে পারেন। ভালো থাকুন।',
      ta: 'நன்றி. உங்கள் தகவல் மற்றும் கோரிக்கை உங்கள் மாவட்ட நல அதிகாரியிடம் பாதுகாப்பாக பதிவு செய்யப்பட்டுள்ளது. நீங்கள் எப்போது வேண்டுமானாலும் உங்கள் விருப்பங்களை மாற்றலாம். பத்திரமாக இருங்கள்.',
      te: 'ధన్యవాదాలు. మీ సమాచారం మరియు సహాయ అభ్యర్థన మీ జిల్లా సంక్షేమ అధికారికి సురಕ್ಷితంగా చేరింది. మీరు ఎప్పుడైనా మీ ప్రాధాన్యతలను మార్చుకోవచ్చు. జాగ్రత్తగా ఉండండి.',
      mr: 'धन्यवाद. आपली माहिती आणि विनंती जिल्हा कल्याण अधिकाऱ्यांकडे सुरक्षितपणे नोंदवली गेली आहे. आपण कधीही आपल्या प्राधान्यांमध्ये बदल करू शकता. काळजी घ्या.',
      kn: 'ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ಮಾಹಿತಿ ಮತ್ತು ಕೋರಿಕೆ ಜಿಲ್ಲಾ ಕಲ್ಯಾಣ ಅಧಿಕಾರಿಗೆ ಸುರಕ್ಷಿತವಾಗಿ ರವಾನೆಯಾಗಿದೆ. ನಿಮ್ಮ ಆದ್ಯತೆಗಳನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು. ಜಾಗರೂಕರಾಗಿರಿ.',
      gu: 'આભાર. તમારી માહિતી અને વિનંતી જિલ્લા કલ્યાણ અધિકારી પાસે સુરક્ષિત રીતે નોંધાઈ ગઈ છે. તમે ગમે ત્યારે તમારી પસંદગી બદલી શકો છો. સાચવજો.',
      or: 'ଧନ୍ୟବାଦ। ଆପଣଙ୍କ ତଥ୍ୟ ଏବଂ ଅନୁରୋଧ ଜିଲ୍ଲା କଲ୍ୟାଣ ଅଧିକାରୀଙ୍କ ନିକଟରେ ସୁରକ୍ଷିତ ଭାବରେ ପଞ୍ଜୀକୃତ ହୋଇଛି। ଆପଣ ଯେକୌଣସି ସମୟରେ ନିଜ ନିଷ୍ପତ୍ତି ବଦଳାଇ ପାରିବେ। ନିଜର ଯତ୍ନ ନିଅନ୍ତୁ।',
    },
    romanizedPromptText: {
      hi: 'Dhanyavaad. Aapka anurodh aur jaankari surakshit roop se Zilla Kalyan Adhikari ko bhej di gayi hai. Aap kisi bhi samay apni prathmiktaen badalne ka adhikaar rakhte hain. Apna khayal rakhein.',
      bn: 'Dhonyobad. Apnar tottho o onurodh nirapode Zilla Adhikarir kache pouchhe geche. Bhalo thakun.',
      ta: 'Nandri. Ungal thagaval Maavatta Nala Adhikaridam paadhukaappaaga pathivu seiyappattulladhu. Bathiramaaga irungal.',
      te: 'Dhanyavadalu. Mee samacharam Zilla Kshema Adhikariki surakshitanga cherindi. Jagrathaga undandi.',
      mr: 'Dhanyavad. Aapli mahiti Jilha Kalyan Adhikaryankade surakshit nondavli geli ahe. Kaalji ghya.',
      kn: 'Dhanyavadagalu. Nimma mahiti Jilla Kalyana Adhikarige surakshitavagi talupide. Jagrookaragiri.',
      gu: 'Aabhar. Tamari mahiti Jilla Kalyan Adhikari paase surakshit rite nondhai gai chhe. Saachavjo.',
      or: 'Dhanyabad. Apananka tathya Jilla Kalyana Adhikarinka nikata-re surakshita bhabare panjikruta hoichi. Nijara jatna niyantu.',
    },
  },

  RESCHEDULED: {
    step: 'CONFIRMATION',
    title: 'Check-in Rescheduled',
    promptText: {
      hi: 'आपकी अनुरोध पर यह चेक-इन कल के लिए पुनर्निर्धारित कर दिया गया है। धन्यवाद।',
      en: 'Your check-in has been rescheduled for tomorrow as requested. Thank you.',
      bn: 'আপনার অনুরোধ অনুযায়ী এই চেক-ইন আগামীকালের জন্য পুনঃনির্ধারণ করা হলো। ধন্যবাদ।',
      ta: 'உங்கள் வேண்டுகோளின்படி இந்த அழைப்பு நாளைக்கு மாற்றப்பட்டுள்ளது. நன்றி.',
      te: 'మీ అభ్యర్థన మేరకు ఈ కాల్ రేపటికి మార్చబడింది. ధన్యవాదాలు.',
      mr: 'आपल्या विनंतीनुसार हा चेक-इन उद्यासाठी पुन्हा शेड्यूल केला आहे. धन्यवाद.',
      kn: 'ನಿಮ್ಮ ಕೋರಿಕೆಯಂತೆ ಈ ಚೆಕ್-ಇನ್ ಅನ್ನು ನಾಳೆಗೆ ಮರುಹೊಂದಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು.',
      gu: 'તમારી વિનંતી મુજબ આ ચેક-ઇન આવતીકાલ માટે પુનઃનિર્ધારિત કરવામાં આવ્યો છે. આભાર.',
      or: 'ଆପଣଙ୍କ ଅନୁରୋଧ କ୍ରମେ ଏହି କଲ୍ ଆସନ୍ତାକାଲି ପାଇଁ ସ୍ଥଗିତ ରଖାଗଲା। ଧନ୍ୟବାଦ।',
    },
    romanizedPromptText: {
      hi: 'Aapke anurodh par yeh check-in kal ke liye punarnirdharit kar diya gaya hai. Dhanyavaad.',
      bn: 'Apnar onurodh onujayi ei check-in agamikaler jonno punonirdharon kora holo. Dhonyobad.',
      ta: 'Ungal vendukolpadi indha azhaippu naalaiku maatrapattulladhu. Nandri.',
      te: 'Mee abhyarthana meraku ee call repatiki marchabadindi. Dhanyavadalu.',
      mr: 'Aaplya vinantinusar ha check-in udyasathi punha schedule kela ahe. Dhanyavad.',
      kn: 'Nimma korikeyante ee check-in annu naalege maruhondisalagide. Dhanyavadagalu.',
      gu: 'Tamari vinanti mujab aa check-in aavatikal mate punahnirdharit karvama aavyo chhe. Aabhar.',
      or: 'Apananka anurodha krame ehi call asantakali pain sthagita rakhagala. Dhanyabad.',
    },
  },

  OPTED_OUT: {
    step: 'CONFIRMATION',
    title: 'Check-ins Paused',
    promptText: {
      hi: 'आपकी इच्छा का सम्मान करते हुए स्वचालित कॉल रोक दिए गए हैं। आप किसी भी समय पुनः शुरू कर सकते हैं।',
      en: 'Respecting your decision, automated check-in calls have been paused. You may reactivate anytime.',
      bn: 'আপনার ইচ্ছাকে সম্মান জানিয়ে স্বয়ংক্রিয় কল বন্ধ করা হলো। আপনি যে কোনো সময় পুনরায় শুরু করতে পারেন।',
      ta: 'உங்கள் முடிவை மதித்து தானியங்கி அழைப்புகள் நிறுத்தப்பட்டுள்ளன. நீங்கள் எப்போது வேண்டுமானாலும் மீண்டும் தொடங்கலாம்.',
      te: 'మీ నిర్ణయాన్ని గౌరవిస్తూ ఆటోమేటిక్ కాల్స్ నిలిపివేయబడ్డాయి. మీరు ఎప్పుడైనా తిరిగి ప్రారంభించవచ్చు.',
      mr: 'आपल्या इच्छेचा आदर करून स्वयंचलित कॉल थांबवण्यात आले आहेत. आपण कधीही पुन्हा सुरू करू शकता.',
      kn: 'ನಿಮ್ಮ ನಿರ್ಧಾರವನ್ನು ಗೌರವಿಸಿ ಸ್ವಯಂಚಾಲಿತ ಕರೆಗಳನ್ನು ನಿಲ್ಲಿಸಲಾಗಿದೆ. ನೀವು ಯಾವಾಗ ಬೇಕಾದರೂ ಪುನರಾರಂಭಿಸಬಹುದು.',
      gu: 'તમારી ઇચ્છાનું સન્માન કરીને ઑટોમેટેડ કૉલ્સ રોકી દેવાયા છે. આપ ગમે ત્યારે ફરી શરૂ કરી શકો છો.',
      or: 'ଆପଣଙ୍କ ନିଷ୍ପତ୍ତିକୁ ସମ୍ମାନ ଜଣାଇ ସ୍ୱୟଂକ୍ରିୟ କଲ୍ ବନ୍ଦ କରାଗଲା। ଆପଣ ଯେକୌଣସି ସମୟରେ ପୁନଃ ଆରମ୍ଭ କରିପାରିବେ।',
    },
    romanizedPromptText: {
      hi: 'Aapki ichha ka samman karte hue swachalit call rok diye gaye hain. Aap kisi bhi samay punah shuru kar sakte hain.',
      bn: 'Apnar ichhake shonman janiye swongkriyo call bondho kora holo. Apni jekono shomoy punoray shuru korte paren.',
      ta: 'Ungal mudivai madhithu thaanaiyangi azhaippugal niruthappattullana. Neengal eppodhu vendumaanalum meendum thodangalaam.',
      te: 'Mee nirnayamni gouravistu automatic calls aapeyabadinavi. Meeru eppudaina thirigi prarambhinchavachu.',
      mr: 'Aaplya ichhecha aadar karun swayan-chalit call thambvinyat aale ahet. Aapan kadhihi punha suru karu shakta.',
      kn: 'Nimma nirdharavannu gouravasi swayamchalita karegalannu nillisalagide. Neevu yaavagabekaroo punararambhisabahudu.',
      gu: 'Tamari ichhanu sanman karine automated calls roki devaya chhe. Aap game tyare fari sharu kari shako chho.',
      or: 'Apananka nispattiku sammana janai swayangkriya call band karagala. Apana jekounasi samayare puna arambha kariparibe.',
    },
  },
};
